### ISSUE TITLE
videfikri rest api has been suspended.

### ISSUE THREAD

**Issue by setyawan12** [VideFrelan/vfbot-wa#5]
bang web rest apinya gak bisa

**Comment by setyawan12** [comment]
![image](https://user-images.githubusercontent.com/74762471/120882476-6b750f00-c602-11eb-8511-5b800e1bd510.png)

**Comment by VideFrelan** [comment]
Hai,

Web tersebut terkena suspend diperkirakan karena melanggar TOS dari pihak Hosting.

TOS yg dimaksud adalah banyaknya traffic masuk ke web videfikri.com, hingga security hostinger menganggap pengunjung website saya adalah BOT illegal

Akan saya usahakan untuk mengembalikan web nya segera, terimakasih.

**Comment by setyawan12** [comment]
> Hai,
> 
> Web tersebut terkena suspend diperkirakan karena melanggar TOS dari pihak Hosting.
> 
> TOS yg dimaksud adalah banyaknya traffic masuk ke web videfikri.com, hingga security hostinger menganggap pengunjung website saya adalah BOT illegal
> 
> Akan saya usahakan untuk mengembalikan web nya segera, terimakasih.

kok belum bisa ya bang

**Comment by VideFrelan** [comment]
@setyawan12 Website **[videfikri.com](https://videfikri.com)** sudah kembali up, tapi masih belum diurus, nikmati yg ada aja ya hhe, silahkan close issue jika tidak ada lagi yg ingin disampaikan
